require 'realself/feed/capped'
require 'realself/feed/feed_error'
require 'realself/feed/getable'
require 'realself/feed/permanent'
require 'realself/feed/redactable'
require 'realself/feed/ttl'
require 'realself/feed/unread_countable'
